# Generated by Django 4.1.7 on 2023-03-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('invoice_no', models.CharField(max_length=20)),
                ('cust_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='invoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('qty', models.IntegerField()),
                ('unitprice', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.invoice')),
            ],
        ),
    ]
